FROM tomcat:10.1.39

RUN apt-get update && apt-get install -y postgresql-client

RUN rm -rf /usr/local/tomcat/webapps/*

COPY myapp.war /usr/local/tomcat/webapps/myapp.war

COPY wait-for-currency-table.sh /usr/local/tomcat/wait-for-currency-table.sh
RUN chmod +x /usr/local/tomcat/wait-for-currency-table.sh

EXPOSE 8080